import { Providers } from './providers'
import './globals.css'
import { Montserrat } from 'next/font/google'
import {Nav} from './components/Nav/Nav'

const font = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Aerolineas API',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <html lang="es" className='dark'>
        <body className={font.className}>
            <Providers>
              <Nav />
              {children}
            </Providers>
        </body>
      </html>
  )
}
